# Generated by Django 2.1.4 on 2019-01-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='modality',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
    ]
