# Generated by Django 2.1.4 on 2019-01-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='modalities',
            field=models.ManyToManyField(to='core.Modality'),
        ),
    ]
