# Generated by Django 2.1.4 on 2019-01-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190106_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='core.Event')),
                ('modalities', models.ManyToManyField(to='core.Modality')),
            ],
        ),
    ]
