version: "3"

services:
  ams:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ams:/ams
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=ams
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=ams
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
