# Generated by Django 2.1.4 on 2019-01-16 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.UUID('69516a9d-5183-4fe5-be63-d3e50d14e480'), max_length=255)),
                ('price', models.FloatField()),
                ('lot', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('half', models.BooleanField(default=False)),
                ('delegation', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
            ],
        ),
    ]
