# Generated by Django 2.1.4 on 2019-01-16 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('e0bef5cc-addc-435a-8725-0e8b2845f180'), max_length=255),
        ),
    ]
