# Generated by Django 2.1.4 on 2019-01-16 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190116_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('3242d4dc-380a-44d3-af3e-f962cbaf2735'), max_length=255),
        ),
    ]
