# Generated by Django 2.1.4 on 2019-01-16 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190116_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('f5dcaecd-e70f-46a9-b444-57b2c2973d0d'), max_length=255),
        ),
    ]
