# Generated by Django 2.1.4 on 2019-01-16 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190116_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('9f03d1e8-6ad5-43ac-a33a-3ca3ab71a188'), max_length=255),
        ),
    ]
