# Generated by Django 2.1.4 on 2019-01-16 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190116_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('57cfa23b-2601-4dbe-9162-e5b9cbf995ab'), max_length=255),
        ),
    ]
