# Generated by Django 2.1.4 on 2019-01-17 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20190116_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('3347e837-2055-48b8-ab33-674f559e1826'), max_length=255),
        ),
    ]
