# Generated by Django 2.1.4 on 2019-01-17 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190117_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('a68f08dd-ef6d-4627-9fcc-29d93a4548aa'), max_length=255),
        ),
    ]
