# Generated by Django 2.1.4 on 2019-01-17 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190117_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('8ee262b7-87a7-4370-b064-5f6c81495568'), max_length=255),
        ),
    ]
