# Generated by Django 2.1.4 on 2019-01-17 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20190117_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('e07b8b85-9e6e-4e85-b2e1-596a9beb39d9'), max_length=255),
        ),
    ]
