# Generated by Django 2.1.4 on 2019-01-17 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20190117_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=uuid.UUID('4b3845f6-bd48-4b17-9db8-eb6e12026a98'), max_length=255),
        ),
    ]
